spring.application.name=cruddemo

#database

spring.datasource.url=jdbc:mysql://localhost:3306/student_tracker
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#turn of spring login banner

spring.main.banner-mode = off

#reduce login level set login level to warn
logging.level.root=warn